# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37fd4747336db4f5fbe97ca9a0cd3a3c2fe88c5c5a2f52ed3aa706860a8aaad0bf23e2c1f696ca3315afc5879523177a5907f9eaa892ed1f79d7b41f139bfd21

test:
  secret_key_base: ab7e81cc8d08e681e9751d8436a955cdfc8f66eb66e7afd8154dc33bc9cfd4884a077ea2a570ea68df5e14e0d406414d696efd9aec38169afbc7aa7c72a9bfc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
